services:
  localdb:
    image: postgres:14.5  # you can pick the most recent version available
    ports:
      - "5432:5432"
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=db-admin
      - POSTGRES_PASSWORD=taq1234
      - POSTGRES_DB=local-data

  testdb:
    image: postgres:14.5
    ports:
      - "5433:5432"
    volumes:
      - ./db/dumps:/app-db-dumps
    environment:
      - POSTGRES_USER=pick_a_username
      - POSTGRES_PASSWORD=pick_a_password
      - POSTGRES_DB=pick_a_db_name
